[tool.ruff]
line-length = 100
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["B905"]

[tool.pyright]
reportMissingImports = "error"
reportMissingTypeStubs = false
reportImplicitOverride = "error"
reportUnusedImport = "error"
reportWildcardImportFromLibrary = "error"
typeCheckingMode = "strict"
pythonVersion = "3.13"
